(defun square-field ()
  (format t "=============================~%")
  (format t "   SQUARE FIELD CALCULATOR   ~%")
  (format t "=============================~%")
  (format t "Enter the side length (in meters): ")
  (let* ((side (read))
         (area (* side side))
         (perimeter (* 4 side)))
    (format t "-----------------------------~%")
    (format t "Side Length : ~a meters~%" side)
    (format t "Area        : ~a sq.meters~%" area)
    (format t "Perimeter   : ~a meters~%" perimeter)
    (format t "=============================~%")))

(square-field)
