(defun calculator ()
  (format t "================================~%")
  (format t "      LISP CALCULATOR           ~%")
  (format t "================================~%")
  (format t " Operations: + - * / ^ %        ~%")
  (format t "================================~%")
  (format t "Enter first number  : ")
  (let* ((num1 (read))
         (dummy (progn (format t "Enter operator (+,-,*,/,^,%) : ") nil))
         (op (read))
         (dummy2 (progn (format t "Enter second number : ") nil))
         (num2 (read))
         (result
           (cond
             ((equal op '+) (+ num1 num2))
             ((equal op '-) (- num1 num2))
             ((equal op '*) (* num1 num2))
             ((equal op '/) 
              (if (= num2 0)
                  (progn (format t "Error: Division by zero!~%") nil)
                  (/ num1 num2)))
             ((equal op '^) (expt num1 num2))
             ((equal op '%) (mod num1 num2))
             (t (progn (format t "Error: Invalid operator!~%") nil)))))
    (when result
      (format t "--------------------------------~%")
      (format t " ~a ~a ~a = ~a~%" num1 op num2 result)
      (format t "================================~%"))))

(calculator)
